name: todo
description: TodoApp with TDD and Cubit.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
